In [1]:
import tensorflow as tf
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, Dense
from tensorflow.keras import regularizers
from sklearn.preprocessing import MinMaxScaler
import pandas as pd

In [2]:
df = pd.read_csv('nation_one_obs.csv')
df.fillna(value=0, inplace=True)
data = df.to_numpy()[:,1:]

In [3]:
scaler = MinMaxScaler()
data_scaled = scaler.fit_transform(data)

In [4]:
input_dim = data.shape[1]  # 8
encoding_dim = 5
# Number of neurons in each Layer [8, 6, 4, 3, ...] of encoders
input_layer = Input(shape=(input_dim, ))
encoder_layer_1 = Dense(30, activation="tanh", activity_regularizer=regularizers.l1(10e-5))(input_layer)
bottleneck = Dense(encoding_dim, activation="tanh")(encoder_layer_1)

In [5]:
# Create encoder model
encoder = Model(inputs=input_layer, outputs=bottleneck)
# Use the model to predict the factors which sum up the information of interest rates.
encoded_data = pd.DataFrame(encoder.predict(data_scaled))
encoded_data.columns = ['feat_'+ str(i) for i in range(encoding_dim)]

In [6]:
encoded_data

       feat_0    feat_1    feat_2    feat_3    feat_4
0   -0.381321  0.232709 -0.237907  0.326690 -0.145447
1   -0.232101  0.737831 -0.685899  0.680312 -0.288058
2   -0.218059  0.650153 -0.491099  0.535676  0.013159
3   -0.309512  0.673318 -0.646911  0.760990 -0.424715
4   -0.129380  0.635373 -0.598177  0.662482 -0.087618
..        ...       ...       ...       ...       ...
190 -0.030087  0.847510 -0.825522  0.692968 -0.466132
191 -0.543211  0.844050 -0.706310  0.832764 -0.019333
192 -0.191488  0.538432 -0.311762  0.421606 -0.137201
193 -0.234804  0.558439 -0.676057  0.761653 -0.012551
194 -0.129406  0.658911 -0.727910  0.733019  0.026024

[195 rows x 5 columns]